### ISSUE TITLE
TC linker fail: segment _text exceeds 64k

### ISSUE THREAD

**Issue by anurudhp** [codelegend/algorithm-compiler#1]
The maximum stack size in turbo c++ is only 64k.
All static data must be changed to either dynamic data, or be stored in files to be buffered at runtime.

Possible changes:
- `importLexerData()` buffers lists from a file.

**Comment by anurudhp** [comment]
other turbo issues:
- `namespaces` not supported.
- `template functions` are parsed on class instantiation, irrespective of whether they are called or not.
- returning local reference to `char *` causes unexpected behaviour

**Comment by anurudhp** [comment]
closing, i dont care about turbo anymore...

**Comment by VThejas** [comment]
Haha lol OK. XD
